name: RequestResponseLog

on: [ push ]

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl

      - name: Install composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Execute static analysis
        run: composer analyse

      - name: Execute tests via PHPUnit
        run: composer test:no-coverage

      - name: Check code style
        run: composer code-style:check
